name: Android Translations
on:
  push:
    branches:
      - master
    paths:
      - "app/src/main/res/**"
      - ".github/workflows/**"

jobs:
  check:
    name: Check
    if: github.repository == 'ashutoshgngwr/noice'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check
        uses: ashutoshgngwr/android-missing-translations@v1
        with:
          markdownTitle: Existing Translations Status
      - uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: 200
          header: translations-report
          message: |
            Please help in translating Noice to your local language. See [CONTRIBUTING.md](https://github.com/ashutoshgngwr/noice/blob/master/docs/CONTRIBUTING.md#translations) for detailed instructions on adding translations.
            Old issue: #108

            ${{ steps.check.outputs.report }}
